### ISSUE TITLE
Default FirebaseApp is not intialized

### ISSUE THREAD

**Issue by alexcchan** [TwilioDevEd/notifications-quickstart-android#18]
Some developers have encountered this error

```
E/AndroidRuntime: FATAL EXCEPTION: IntentService[BindingIntentService]
    Process: com.twilio.notify.quickstart, PID: 3405
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.twilio.notify.quickstart. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.1:219)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source:1)
        at com.twilio.notify.quickstart.BindingIntentService.onHandleIntent(BindingIntentService.java:71)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

and worked around by downgrading dependency:
https://github.com/TwilioDevEd/notifications-quickstart-android/blob/master/build.gradle#L11

to
```
        classpath 'com.google.gms:google-services:4.0.1'
```

as mentioned here:

https://stackoverflow.com/questions/40081539/default-firebaseapp-is-not-initialized

**Comment by TJGreen97** [comment]
A year later and I have come across this same issue. An update would be good to show it working now that FirebaseInstanceIdService has been deprecated.

**Comment by chandrikaReddyBunga** [comment]
what we enter in identity textfeild for binding .
